# Generated by Django 3.1.5 on 2021-02-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210213_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlikescount',
            old_name='post_id',
            new_name='post',
        ),
    ]
